### ISSUE TITLE
Feature request: Develop a cron job that automatically runs the process so that the sheets are always up to date

### ISSUE THREAD

**Issue by ciderpunx** [UKParlDataSheets/UKParlDataSheets.github.io#2]
It would be good if there was a script that could be scheduled to run as a cron job that would update the sheets as and when needed.

The way I see this working would require on a server "somewhere" that both repos were cloned. 

A "script" user would be set up with a passwordless ssh key and access to this repository (the github.io one).

The script would run as a cron job and would do this:
- Pull down the XML data from the Parliament API
- Run the XML files through the php script to create the CSVs
- If the CSVs had changed (according to git status -s) then it would do a git commit and push to the repository.

**Comment by jarofgreen** [comment]
I was thinking ..... 
-  UKParlDataSheets.github.io is a static HTML page with links only
-  There is a Python\* script ...
- .... that AWS Lambda runs once per day ...
-  ... that dumps the CSV's in a S3 bucket ...
-  .... that is just served as a website, linked from UKParlDataSheets.github.io

But let me have a good look at #3 - I appear to be on the worlds slowest connection here so not now tho.

[ \* Or Java or Node. But it doesn't support PHP, and if I was doing it it would be Python or Java and I suspect Python would be quicker to get going in. ]

**Comment by ciderpunx** [comment]
Sure, Python is nice, but I am fine with whatever. Maybe we add an issue to rewrite the whole thing in Python (heh). 

I think there's some value to having the sheets under version control; it'd be nice to be able to see diffs after an election,  for example and Parliament doesn't maintain historical data. Maybe that makes things more complex than needed though. 

I've not used s3 before, because Amazon I assume that there isn't a cost unless you're dealing with lots of requests? If there was then we could do something clever to use cloudflare as a cache or use openshift or something like that...

**Comment by jarofgreen** [comment]
Closing - have rewritten in Python :-)

Will discuss versioning elsewhere ...
